### ISSUE TITLE
Morning session code review 23.12.2021

### ISSUE THREAD

**Issue by Hombre2014** [arnrdn/leaderboard#3]
Nice job, Nana. It seems that everything looks fine and it is hard to find something that needs to be corrected.
Here is our input:
- Please, change the title of the web page `<title>Wbpack Exercise</title>`

**Comment by tmampa** [comment]
Great job, Nana. The code looks very short and easy to read. Keep up the good work and happy coding!

## Optional changes

- Fix the live link
